feat : add icons and link in the founder card
firenzedev/firenze.dev pull request #15
Opened 2023-02-10 17:56 UTC by AlessioChen

2023-02-11 15:33 UTC, Spyna commented
Grazie Alessio, 
ho segnato alcuni commenti nel codice.

2023-02-11 19:52 UTC, AlessioChen commented
Ciao, io non vedo i commenti.

2023-02-12 10:35 UTC, Spyna requested changes

2023-02-12 16:54 UTC, Spyna approved these changes

2023-02-12 16:55 UTC, merged