Feature/sponsorship page UI
firenzedev/firenze.dev pull request #26
Opened 2023-02-24 16:15 UTC by mino89

- Ui adjustments for sponsorship pages
- Creation of reusable hero component
- Creation of reusable bubble component

2023-02-24 16:28 UTC, Spyna requested changes
ho messo dei commenti sparsi un po' in qua e la nel codice

2023-02-24 16:28 UTC, Spyna commented on components/Pages/Sponsorship/Sponsorship.tsx
> +          <H4>
ci toglierei l' H4 per uniformare il font con la sezione accanto
![image](https://user-images.githubusercontent.com/13762470/221232637-68360ad7-4790-4e83-b564-d61140b90a79.png)

2023-02-24 16:28 UTC, Spyna commented on components/Pages/Sponsorship/FAQ.tsx
> +              <div className="m-1 mr-2 w-12 h-12 relative flex justify-center items-center rounded-full bg-blue-700 text-lg text-white uppercase">Q</div>
su mobile la Q su stringe, magari si può pensare di mandarlo a capo

2023-02-24 16:28 UTC, Spyna commented on components/Hero/Hero.tsx
> +export default function Hero({ title, subtitle, actions, image }: HeroProps) {
Su mobile metterei allineato a sinistra

2023-02-24 16:30 UTC, Spyna commented on components/Hero/Hero.tsx
> +export default function Hero({ title, subtitle, actions, image }: HeroProps) {
Metteri anche una call to action che manda alla sezione in basso: "come diventare sponsor"

2023-02-24 16:33 UTC, pixel13 commented
C'è anche un typo da correggere sul titolo (Divanta --> Diventa): 

https://github.com/firenzedev/firenze.dev/blob/390db2fef9ffc425e4add160aac605659fb70fea/pages/sponsorship.tsx#L8

2023-02-24 17:11 UTC, mino89 commented on components/Pages/Sponsorship/Sponsorship.tsx
> +          <H4>
Inserito un h2 e allineati meglio

2023-02-24 17:11 UTC, mino89 commented on components/Pages/Sponsorship/FAQ.tsx
> +              <div className="m-1 mr-2 w-12 h-12 relative flex justify-center items-center rounded-full bg-blue-700 text-lg text-white uppercase">Q</div>
sistemato, settato shrink a 0 cosi mantiene una larghezza fissa

2023-02-24 17:13 UTC, mino89 commented on components/Hero/Hero.tsx
> +export default function Hero({ title, subtitle, actions, image }: HeroProps) {
Quindi riporteresti lo stesso comportamento anche nella hero in home? 
Ho creato un componente unificato per gestire tutte le hero, eventualmente ci potrei mettere un controllo per l'alignment

2023-02-24 17:35 UTC, mino89 commented on components/Hero/Hero.tsx
> +export default function Hero({ title, subtitle, actions, image }: HeroProps) {
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/5948240/221248826-1fe3814d-8847-43ad-ad52-8e24f2e89077.png">
ho qualche dubbio sul testo

2023-03-08 07:56 UTC, Spyna approved these changes

2023-03-08 07:58 UTC, merged